### ISSUE TITLE
Upgrade action to node16

### ISSUE THREAD

**Issue by tuerpisch** [ntsd/auto-request-changes-action#2]
https://github.com/ntsd/auto-request-changes-action/blob/86a93838a6876ce8406541be4fd2cbf99c27e09f/action.yml#L18

The action should be upgraded using at least node16.
Node12 is already EoL for over a year now.
At some point, GitHub will not support running these anymore.
[See here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

**Comment by ntsd** [comment]
> https://github.com/ntsd/auto-request-changes-action/blob/86a93838a6876ce8406541be4fd2cbf99c27e09f/action.yml#L18
> 
> The action should be upgraded using at least node16. Node12 is already EoL for over a year now. At some point, GitHub will not support running these anymore. [See here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

Upgrade in Version 3

https://github.com/ntsd/auto-request-changes-action/releases/tag/v3.0.0
